pages/urls.py
from django.urls import path

from .views import (
    ArticleArchiveIndexView,
    ArticleDayArchiveView,
    ArticleDetailView,
    ArticleMonthArchiveView,
    ArticleYearArchiveView,
    ShotgunArchiveLimited,
    ShotgunCreateFormView,
)

app_name = "pages"
urlpatterns = [
    path("", ArticleArchiveIndexView.as_view(), name="article_index"),
    # path("shotgun/", ShotgunArchiveIndexView.as_view(), name="shotgun_index"),
    path("<int:year>/", ArticleYearArchiveView.as_view(), name="article_year"),
    path(
        "<int:year>/<int:month>/",
        ArticleMonthArchiveView.as_view(),
        name="article_month",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/",
        ArticleDayArchiveView.as_view(),
        name="article_day",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug>/",
        ArticleDetailView.as_view(),
        name="article_detail",
    ),
    path(
        "shot/<int:pk>/",
        ShotgunArchiveLimited.as_view(),
        name="shotgun_detail",
    ),
    path(
        "shot/add/",
        ShotgunCreateFormView.as_view(),
        name="shotgun_create",
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from filebrowser.sites import site

from pages.views import HomePageTemplateView
from users.views import (
    ContactFormView,
    HTMXLoginView,
    HTMXLogoutView,
    HTMXSignupView,
    ProfileChangeView,
    ProfileDeleteView,
    TestedEmailView,
    TestedPasswordChangeView,
    TestedPasswordResetView,
    TestedPasswordSetView,
)

from .views import SelectLanguageTemplateView, search_results

sitemaps = {
    "flatpages": FlatPageSitemap,
}

urlpatterns = [
    path("admin/filebrowser/", site.urls),
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("accounts/login/", HTMXLoginView.as_view(), name="account_login"),
    path("accounts/logout/", HTMXLogoutView.as_view(), name="account_logout"),
    path("accounts/signup/", HTMXSignupView.as_view(), name="account_signup"),
    path("accounts/contact/", ContactFormView.as_view(), name="account_contact"),
    path("accounts/profile/", ProfileChangeView.as_view(), name="account_profile"),
    path(
        "accounts/profile/delete/", ProfileDeleteView.as_view(), name="account_delete"
    ),
    path(
        "accounts/password/change/",
        TestedPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/set/", TestedPasswordSetView.as_view(), name="password_set"
    ),
    path(
        "accounts/password/reset/",
        TestedPasswordResetView.as_view(),
        name="password_reset",
    ),
    path("accounts/email/", TestedEmailView.as_view(), name="account_email"),
    path("accounts/", include("allauth.urls")),
    path("docs/", include("django.contrib.flatpages.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("build-api/", include("buildings.api_urls")),
    path("tinymce/", include("tinymce.urls")),
]

urlpatterns += i18n_patterns(
    path("", HomePageTemplateView.as_view(), name="home"),
    path(_("search/"), search_results, name="search_results"),
    path(
        _("select-language/"),
        SelectLanguageTemplateView.as_view(),
        name="select_language",
    ),
    path(_("articles/"), include("pages.urls", namespace="pages")),
    path(_("buildings/"), include("buildings.urls", namespace="buildings")),
    path(_("geotree/"), include("djeotree.urls", namespace="geotree")),
    path(_("geocad/"), include("djeocad.urls", namespace="djeocad")),
    path(_("timeline/"), include("timeline.urls", namespace="timeline")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from filebrowser.fields import FileBrowseField
from filer.fields.image import FilerImageField
from tinymce.models import HTMLField

from project.utils import check_wide_image

from .choices import ICONS

User = get_user_model()


class Logo(models.Model):

    title = models.CharField(
        _("Title"),
        max_length=50,
    )
    fb_image = FileBrowseField(
        _("Image"),
        max_length=200,
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        directory="images/",
        null=True,
    )

    class Meta:
        verbose_name = _("Logo")
        verbose_name_plural = _("Logo")


class FooterLink(models.Model):

    title = models.CharField(
        _("Title"),
        max_length=50,
    )
    link = models.URLField(
        _("Link"),
        max_length=200,
    )
    icon = models.CharField(
        max_length=50, choices=ICONS, verbose_name=_("Icon"), default="fa-external-link"
    )

    class Meta:
        verbose_name = _("Footer link")
        verbose_name_plural = _("Footer links")


class HomePage(models.Model):

    title = models.CharField(
        _("Title"),
        help_text=_("Appears on first image"),
        max_length=50,
        null=True,
        blank=True,
    )
    intro = models.CharField(
        _("Subtitle"),
        max_length=100,
        null=True,
        blank=True,
        help_text=_("Website in few words"),
    )
    body = HTMLField(
        _("Text"), null=True, blank=True, help_text=_("Talk about this website")
    )

    def __str__(self):
        if self.title:
            return self.title
        return _("Home Page - ") + str(self.id)

    class Meta:
        verbose_name = _("Home Page")
        verbose_name_plural = _("Home Pages")


class HomePageCarousel(models.Model):

    home = models.ForeignKey(
        HomePage,
        on_delete=models.CASCADE,
        related_name="homepage_carousel",
        verbose_name=_("Home Page"),
    )
    fb_image = FileBrowseField(
        _("Image"),
        max_length=200,
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        directory="images/",
    )
    description = models.CharField(
        _("Description"),
        help_text=_("Will be used in captions"),
        max_length=100,
        null=True,
        blank=True,
    )
    position = models.PositiveSmallIntegerField(_("Position"), null=True)

    class Meta:
        verbose_name = _("Home page carousel")
        verbose_name_plural = _("Home page carousels")
        ordering = [
            "position",
        ]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        check_wide_image(self.fb_image)


def default_intro():
    # following try/except for test to work
    try:
        current_site = Site.objects.get_current()
        return _("Another article by %(name)s!") % {"name": current_site.name}
    except Site.DoesNotExist:
        return _("Another article by this site!")


class Article(models.Model):
    slug = models.SlugField(max_length=60, null=True, editable=False)
    title = models.CharField(
        _("Title"), help_text=_("The title of the article"), max_length=50
    )
    intro = models.CharField(_("Introduction"), default=default_intro, max_length=100)
    body = HTMLField(_("Text"), null=True)
    date = models.DateField(
        _("Date"),
        default=now,
    )
    last_updated = models.DateTimeField(editable=False, null=True)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_("Author")
    )

    def get_path(self):
        return reverse(
            "pages:article_detail",
            kwargs={
                "year": self.date.year,
                "month": self.date.month,
                "day": self.date.day,
                "slug": self.slug,
            },
        )

    def get_previous(self):
        try:
            return self.get_previous_by_date()
        except Article.DoesNotExist:
            return

    def get_next(self):
        try:
            return self.get_next_by_date()
        except Article.DoesNotExist:
            return

    def save(self, *args, **kwargs):
        if not self.id:
            super(Article, self).save(*args, **kwargs)
        self.slug = slugify(self.title) + "-" + str(self.id)
        self.last_updated = now()
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ("-date",)


class ArticleCarousel(models.Model):

    home = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name="article_carousel",
        verbose_name=_("Article"),
    )
    fb_image = FileBrowseField(
        _("Image"),
        max_length=200,
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        directory="images/",
    )
    description = models.CharField(
        _("Description"),
        help_text=_("Will be used in captions"),
        max_length=100,
        null=True,
        blank=True,
    )
    position = models.PositiveSmallIntegerField(_("Position"), null=True)

    class Meta:
        verbose_name = _("Article carousel")
        verbose_name_plural = _("Article carousels")
        ordering = [
            "position",
        ]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        check_wide_image(self.fb_image)


class Shotgun(models.Model):
    title = models.CharField(
        _("Title"), help_text=_("The title of the article"), max_length=100
    )
    body = HTMLField(_("Text"), null=True)
    date = models.DateField(
        _("Date"),
        default=now,
    )

    class Meta:
        verbose_name = _("Shotgun article")
        verbose_name_plural = _("Shotgun articles")
        ordering = [
            "-date",
        ]

    def get_card_width(self):
        for img in self.shotgun_image.all():
            if img.filer_image.width > img.filer_image.height:
                return "max-width: 960px"
        return "max-width: 480px"


class ShotgunImage(models.Model):
    shot = models.ForeignKey(
        Shotgun,
        on_delete=models.CASCADE,
        related_name="shotgun_image",
        verbose_name=_("Article"),
    )
    description = models.CharField(
        _("Description"),
        help_text=_("Used in captions"),
        max_length=200,
        null=True,
        blank=True,
    )
    fb_image = FileBrowseField(
        _("Image"),
        max_length=200,
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        directory="images/shotgun/",
        null=True,
    )
    filer_image = FilerImageField(
        null=True, related_name="shotgun_filer_image", on_delete=models.SET_NULL
    )
    position = models.PositiveSmallIntegerField(_("Position"), null=True)

    class Meta:
        verbose_name = _("Shotgun image")
        verbose_name_plural = _("Shotgun images")
        ordering = [
            "position",
        ]

pages/templates/pages/includes/article_list.html
{% load i18n %}
{% load fb_versions %}

{% if articles %}
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
    {% for article in articles %}
      <div class="col">
        <div class="card h-100">
          <div class="card-header">
            <h4 class="link-primary"
                hx-get="{{ article.get_path }}"
                hx-target="#content"
                hx-push-url="true">{{ article.title }}
            </h4>
          </div>
          <div class="card-body">
            {% if article.article_carousel.first %}
              <img class="card-img-top"
                   src="{% version article.article_carousel.first.fb_image 'popup' %}"
                   alt="{{ article.intro }}">
            {% endif %}
            <p>
              {{ article.date|date:"d M Y" }}
              {% if article.author %}
                - {% translate "by"%}
                {% if article.author.get_avatar %}
                  <img class="rounded-circle"
                       heigth="20px"
                       width="20px"
                       src="{{ article.author.get_avatar }}"
                       alt="">
                {% endif %}
                {{ article.author.get_full_name }}
              {% endif %}
            </p>
            <p>
              <em>{{ article.intro }}</em>
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% else %}
  <p>{% translate "No articles available" %}</p>
{% endif %}

pages/templates/pages/includes/infinite_scroll.html
{% include "pages/includes/article_list.html" %}
{% if page_obj.has_next %}
  <p
    hx-get="{% url 'pages:article_index' %}?page={{ page_obj.next_page_number }}"
    hx-trigger="revealed"
    hx-swap="afterend">
  </p>
{% endif %}

pages/templates/pages/includes/infinite_shotgun.html
{% include "pages/includes/shotgun_list.html" %}
{% if page_obj.has_next %}
  <p
    {% if shot %}
      hx-get="{% url 'pages:shotgun_detail' pk=shot.id %}?page={{ page_obj.next_page_number }}"
    {% else %}
      hx-get="{% url 'shotgun_index' %}?page={{ page_obj.next_page_number }}"
    {% endif %}
    hx-trigger="revealed"
    hx-swap="afterend">
  </p>
{% endif %}

pages/templates/pages/includes/shotgun_card.html
{% load i18n %}
{% load thumbnail %}

<div class="card-header">
  <h4>
    {{ shot.title | safe }}
  </h4>
</div>
<div class="card-body">
  {% if shot.shotgun_image %}
    {% for image in shot.shotgun_image.all %}
      <div class="text-center">
        <figure class="figure">
          <img class="figure-img img-fluid"
            src="{% thumbnail image.filer_image 0x800 %}"
            alt="{{ image.description }}">
          <figcaption class="figure-caption">
            {{ image.description | default_if_none:'' }}
          </figcaption>
        </figure>
      </div>
    {% endfor %}
  {% endif %}
  <p>
    {{ shot.date|date:"d M Y" }}
  </p>
  <p>
    {{ shot.body | safe }}
  </p>
  {% if perms.pages.add_shotgun %}
    <a href="/admin/pages/shotgun/{{ shot.id}}/change/">
      {% translate "Modify" %}
    </a>
  {% endif %}
</div>

pages/templates/pages/includes/shotgun_list.html
{% load i18n %}

{% if shots %}
  {% for shot in shots %}
    <div class="card mx-auto" style="margin-bottom: 20px;{{ shot.get_card_width }}">
      {% include "pages/includes/shotgun_card.html" %}
    </div>
  {% endfor %}
{% else %}
  <p>{% translate "No articles available" %}</p>
{% endif %}