pages/urls.py
from django.urls import path

from .views import (
    ArticleArchiveIndexView,
    ArticleDayArchiveView,
    ArticleDetailView,
    ArticleMonthArchiveView,
    ArticleYearArchiveView,
    ShotgunArchiveLimited,
    ShotgunCreateFormView,
)

app_name = "pages"
urlpatterns = [
    path("", ArticleArchiveIndexView.as_view(), name="article_index"),
    # path("shotgun/", ShotgunArchiveIndexView.as_view(), name="shotgun_index"),
    path("<int:year>/", ArticleYearArchiveView.as_view(), name="article_year"),
    path(
        "<int:year>/<int:month>/",
        ArticleMonthArchiveView.as_view(),
        name="article_month",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/",
        ArticleDayArchiveView.as_view(),
        name="article_day",
    ),
    path(
        "<int:year>/<int:month>/<int:day>/<slug>/",
        ArticleDetailView.as_view(),
        name="article_detail",
    ),
    path(
        "shot/<int:pk>/",
        ShotgunArchiveLimited.as_view(),
        name="shotgun_detail",
    ),
    path(
        "shot/add/",
        ShotgunCreateFormView.as_view(),
        name="shotgun_create",
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from filebrowser.sites import site

from pages.views import HomePageTemplateView
from users.views import (
    ContactFormView,
    HTMXLoginView,
    HTMXLogoutView,
    HTMXSignupView,
    ProfileChangeView,
    ProfileDeleteView,
    TestedEmailView,
    TestedPasswordChangeView,
    TestedPasswordResetView,
    TestedPasswordSetView,
)

from .views import SelectLanguageTemplateView, search_results

sitemaps = {
    "flatpages": FlatPageSitemap,
}

urlpatterns = [
    path("admin/filebrowser/", site.urls),
    path("grappelli/", include("grappelli.urls")),  # grappelli URLS
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("accounts/login/", HTMXLoginView.as_view(), name="account_login"),
    path("accounts/logout/", HTMXLogoutView.as_view(), name="account_logout"),
    path("accounts/signup/", HTMXSignupView.as_view(), name="account_signup"),
    path("accounts/contact/", ContactFormView.as_view(), name="account_contact"),
    path("accounts/profile/", ProfileChangeView.as_view(), name="account_profile"),
    path(
        "accounts/profile/delete/", ProfileDeleteView.as_view(), name="account_delete"
    ),
    path(
        "accounts/password/change/",
        TestedPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "accounts/password/set/", TestedPasswordSetView.as_view(), name="password_set"
    ),
    path(
        "accounts/password/reset/",
        TestedPasswordResetView.as_view(),
        name="password_reset",
    ),
    path("accounts/email/", TestedEmailView.as_view(), name="account_email"),
    path("accounts/", include("allauth.urls")),
    path("docs/", include("django.contrib.flatpages.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("build-api/", include("buildings.api_urls")),
    path("tinymce/", include("tinymce.urls")),
]

urlpatterns += i18n_patterns(
    path("", HomePageTemplateView.as_view(), name="home"),
    path(_("search/"), search_results, name="search_results"),
    path(
        _("select-language/"),
        SelectLanguageTemplateView.as_view(),
        name="select_language",
    ),
    path(_("articles/"), include("pages.urls", namespace="pages")),
    path(_("buildings/"), include("buildings.urls", namespace="buildings")),
    path(_("geotree/"), include("djeotree.urls", namespace="geotree")),
    path(_("geocad/"), include("djeocad.urls", namespace="djeocad")),
    path(_("timeline/"), include("timeline.urls", namespace="timeline")),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/pages/htmx/article_detail.html
{% load i18n %}

{% include 'pages/gallery.html' %}
<div class="card mx-auto" style="max-width: 960px; margin-top: 60px">
  <div class="card-header">
    <h3>{{ article.title }}</h3>
    <p>
      <em>{{ article.intro }}</em>
      - {{ article.date|date:"d M Y" }}
      {% if article.author %}
        - {% translate "by"%}
        {% if article.author.get_avatar %}
          <img class="rounded-circle"
               heigth="20px"
               width="20px"
               src="{{ article.author.get_avatar }}"
               alt="">
        {% endif %}
        {{ article.author.get_full_name }}
      {% endif %}
    </p>
  </div>
  <div class="card-body">
    {{ article.body | safe }}
    <hr class="mb-4">
    <div class="row">
      <div class="col col-6">
        {% with prev=article.get_previous %}
          {% if prev %}
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            <a class="link-primary"
               hx-get="{{ prev.get_path }}"
               hx-target="#content"
               hx-push-url="true">{{ prev.title }}
            </a>
          {% endif %}
        {% endwith %}
      </div>
      <div class="col col-6 text-end">
        {% with next=article.get_next %}
          {% if next %}
            <a class="link-primary"
               hx-get="{{ next.get_path }}"
               hx-target="#content"
               hx-push-url="true">{{ next.title }}
            </a>
            <i class="fa fa-arrow-right" aria-hidden="true"></i>
          {% endif %}
        {% endwith %}
      </div>
    </div>
  </div>
</div>

pages/templates/pages/htmx/article_index.html
{% load i18n %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container">
    <div class="card mx-auto" style="max-width: 960px; margin-top: 60px">
      <div class="card-header">
        <h3>{% translate 'Articles' %}</h3>
      </div>
      <div class="card-body">
        {% include "pages/includes/infinite_scroll.html" %}
      </div>
    </div>
  </div>
</main>
{% include 'footer.html' %}

pages/templates/pages/htmx/home.html
{% load i18n %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container">
    {% include 'pages/gallery.html' %}
    <div class="card mx-auto" style="max-width: 960px; margin-top: 20px;">
      {% if page.intro %}
        <div class="card-header">
          <h4 class="text-left"><strong><em>{{ page.intro }}</em></strong></h4>
        </div>
      {% endif %}
      {% if page.body %}
        <div class="card-body">
          <p class="text-left">{{ page.body | safe }}</p>
        </div>
      {% endif %}
    </div>
    <div class="card mx-auto" style="max-width: 960px; margin-top: 20px;">
      <div class="card-header">
        <h3 class="link-primary"
            hx-get="{% url 'pages:article_index' %}"
            hx-target="#menucont"
            hx-push-url="true">{% translate 'Articles' %}
        </h3>
      </div>
      <div class="card-body">
        {% include "pages/includes/article_list.html" %}
      </div>
    </div>
  </div>
</main>
{% include 'footer.html' %}

pages/templates/pages/htmx/shotgun_create.html
{% load i18n %}
{% load bootstrap5 %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container" style="margin-top: 60px">
    <div class="card mx-auto" style="max-width: 480px;">
      <div class="card-header">
        <h3>{% trans "Add shot article" %}</h3>
      </div>
      <div class="card-body">
        <form
          hx-post="{% url 'pages:shotgun_create' %}"
          hx-target="#menucont"
          hx-encoding="multipart/form-data"
          hx-push-url="true">
          {% bootstrap_form form %}
          <button class="btn btn-primary" type="submit">{% trans "Add article" %}</button>
        </form>
      </div>
    </div>
  </div>
</main>
{% include 'footer.html' %}

pages/templates/pages/htmx/shotgun_detail.html
<div class="card mx-auto" style="margin-top: 60px; margin-bottom: 20px;{{ shot.get_card_width }}">
  {% include "pages/includes/shotgun_card.html" %}
</div>

pages/templates/pages/htmx/shotgun_index.html
{% load i18n %}

{% include 'navbar.html' %}
<main class="flex-shrink-0">
  <div id="content" class="container" style="margin-top: 60px">
    {% include "pages/includes/infinite_shotgun.html" %}
  </div>
</main>
{% include 'footer.html' %}